FROM debian:bullseye

RUN apt-get -y update \
	&& apt-get -y upgrade \
	&& apt-get -y install nginx

RUN apt-get -y install curl  openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt -subj "/C=MO/ST=khouribga/L=khouribga/O=inception/CN=saboulal.42.fr"

COPY ./conf/nginx.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
